# Generated by Django 3.0.8 on 2020-07-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=13)),
                ('telefono', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=20)),
                ('matricula', models.CharField(max_length=20)),
                ('diaentrada', models.CharField(max_length=10)),
                ('vahiculo', models.CharField(max_length=10)),
                ('vigencia', models.BooleanField()),
                ('saldoapagar', models.IntegerField()),
            ],
        ),
    ]
