# Generated by Django 3.0.8 on 2020-07-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chequeo', '0002_remove_clientes_saldoapagar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='diaentrada',
            field=models.CharField(max_length=100),
        ),
    ]
