# Generated by Django 3.0.8 on 2020-07-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chequeo', '0003_auto_20200720_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='dias',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
